#!/usr/bin/env bash

DOTS_BIN_DIR=$(pwd)
source lib/output
source lib/rc
source commands/install
source commands/uninstall
source commands/list

#
# Do something depending on the passed arguments.
#
if [ $# -eq 0 ]
    then
        help

        exit 1
    else
        case "$1" in
            "--help" | "-h" | "help")
                _dots_command_help
                ;;
            "install")
                _dots_command_install $2
                ;;
			"uninstall")
				_dots_command_uninstall $2
				;;
			"ls" | "list")
				_dots_command_list
				;;
            *)
                dots_output_fail "Fatal Error: Unknown argument '$1'. For help regarding the dotfiles CLI execute 'dots help'."

                exit 1
                ;;
        esac
fi

exit 0
